### PR TITLE
- reformatted requirement as per pipenv standards

### PR DESCRIPTION
**Pull request by why-not-try-calmer**
I like [Pipenv](https://pipenv-fork.readthedocs.io/en/latest/index.html). Are you ok to use it as our main Python dependency manager? If not it's not a big deal, we can still merge from this PR and then I won't bother you anymore. I just need it to get started.

### CODE REVIEW

**Review by KaratekHD — COMMENTED** [review]
Is it a good idea to have fixed version numbers? I would not do this unless we really depend on a specific version

**Comment by why-not-try-calmer** [comment]
> Is it a good idea to have fixed version numbers? I would not do this unless we really depend on a specific version

It ensures that we are all working with the same tools. Otherwise there is no guarantee that X or Y has pulled out the last version.

**Comment by KaratekHD** [comment]
> > Is it a good idea to have fixed version numbers? I would not do this unless we really depend on a specific version
> 
> It ensures that we are all working with the same tools. Otherwise there is no guarantee that X or Y has pulled out the last version. It's a can of worms for bugs. Imagine having a bug because two versions don't play nice with one another, but we have never found this out because we always were using different versions...
> 
> Another last reason to pin dependencies is that it makes it easier to rollback to a specific working combination should we notice that another combination fails.

Ok, I see that.

**Comment by KaratekHD** [comment]
I will also add pytest to the requirements later, or if you come around to it you can do that @why-not-try-calmer

**Pull request merged**
