### PR TITLE
Implement basic caching

### PR DESCRIPTION
**Pull request by KaratekHD**
So I built some basic caching using Redis. My idea is that we put all the arguments for a search or sth similar in a `QueryObject` which makes everything easier. We can just put the `@cache` decorator on top of a function that does the upper and it gets cached. Merging this would close #6

### CODE REVIEW

**Review by muadib — APPROVED** [review]

**Comment by KaratekHD** [comment]
I think it would be a good idea to have this save the time it cached sth too, so that we can overwrite the cache if it is too old

**Comment by KaratekHD** [comment]
This change adds basic tests for the caching using pytest. You can run the tests by executing `pytest`

**Comment by KaratekHD** [comment]
Alright, so these tests fail because in the GitHub Action there is no Redis Server running... I'm gonna try to find a solution for that soon.

**Comment by why-not-try-calmer** [comment]
Thanks for this PR, that's a nice decorate right here. However I think we'll want to use something a bit more robust and feature-ful than the plain redis package. How about [pottery](https://github.com/brainix/pottery)? I am looking in particular at ContextTimer to solve the issue of different lifetimes for cached items, and `redis_cache` + `CachedOrderedDict` look super useful.

**Review by why-not-try-calmer — APPROVED** [review]

**Comment by why-not-try-calmer** [comment]
If you approve by approval and of my 2 commits, you can merge

**Pull request merged**
