### PR TITLE
Use python configparser for config file

### PR DESCRIPTION
**Pull request by KaratekHD**
This is the "Python way" of doing configuration files according to https://docs.python.org/3/library/configparser.html.

### CODE REVIEW

**Comment by why-not-try-calmer** [comment]
Thanks for looking into that, it looks very clean and I like it. As soon as there is a proper importation logic we can merge!

**Comment by onuralpszr** [comment]
@why-not-try-calmer  I noticed that sensitive infos you may want to check out again please :)

**Comment by why-not-try-calmer** [comment]
> @why-not-try-calmer I noticed that sensitive infos you may want to check out again please :)

Jens added the file to `.gitignore`, but he has to share it at least once so that it makes it into the repo...

**Comment by KaratekHD** [comment]
It's literally online, Redis password and my openSUSE credentials.

**Comment by why-not-try-calmer** [comment]
> @why-not-try-calmer I noticed that sensitive infos you may want to check out again please :)

Indeed, textbook case of compromised credentials, thanks for you vigilance, all passwords in the scope of this breach have been changed.

**Pull request closed without merging**
