### PR TITLE
captcha

### LINKED ISSUE #44: Captchas
The aim in resolving this issue is to write a module for @karatekbot in telegram.

### PR DESCRIPTION
**Pull request by MehmetKay-sudo**
In this section i will program a captcha_bot with the following instructions and will interact with the user.

captcha // user interaction

    1. User joins a chat
    2. [bot] The bot of the platform the user is on reacts, maybe checks of it already knows the user from another chat and if not, proceeds
    3. [bot] sends request to the defrag API and asks for a captcha
    4. [API] generates a captcha image, together with an ID, and stores the solution for the captcha together with the ID. Returns ID and image to the bot.
    5. [bot] sends the captcha image to the group. Keeps the message ID of the image associated with the captcha ID in memory.
    6. [user] Sends solutions to the captcha. If not, [bot] bans user.
    7. [bot] sends input to defrag, together with captcha ID
    8. [API] validates input based on the stored solution associated with the captcha ID
    9. [API] returns a boolean that includes wether the user completed the captcha correctly
    10. [bot] If the boolean from 9. is true, delete the captcha image and allow the user to send messages, if it is false ban the user

### CODE REVIEW

**Comment by KaratekHD** [comment]
You have a bunch of conflicts already, before implementing your changes. This happens when your forked repository is behind the upstream repository and will make your life harder. It might make sense to delete that branch and update your repo, so that you do not have to deal with the merge requests

**Comment by onuralpszr** [comment]
@MehmetKay-sudo  also you should explain your changes in "commit" section in a better way just "test" is not the ideal way to explain what is happened, Plus you should split your commits as well.

**Comment by KaratekHD** [comment]
I'm gonna close this since it is inactive for 23 days. Feel free to open a new PR as soon as your feature is ready 😉

**Comment by MehmetKay-sudo** [comment]
Thank you Jens. I am busy right now, due to my internship at a local school. I am working on it.

Bests,
Mehmet

Von meinem iPhone gesendet

**Pull request closed without merging**
