### PR TITLE
Wikis search

### PR DESCRIPTION
**Pull request by why-not-try-calmer**
Wikis search. Basic but functional.
Pleas do not merge before #61 as it's based on it.

### CODE REVIEW

**Comment by KaratekHD** [comment]
This wiki search has a fundamental problem, as it does only find a friction of the actual available wiki entries. Everything that begins with `SDB:`, `HCL:`, `openSUSE:`, `User:` etc. is not there with our API. 
Take this example:
```bash
$ curl -X 'GET' \
  'http://localhost:8000/wikis/search/?keywords=DNF' \
  -H 'accept: application/json'
```
returns
```json
{
  "query": {
    "service": "wikis",
    "item_key": null
  },
  "results_count": 5,
  "results": [
    {
      "wordcount": 7300,
      "timestamp": 1593108333,
      "title": "Features 15.2",
      "snippet": "of <span class=\"searchmatch\">DNF</span> called &quot;Micro <span class=\"searchmatch\">DNF</span>&quot; is now included. It is designed to be used for doing simple package management actions when you don't need full-blown <span class=\"searchmatch\">DNF</span> and",
      "url": "https://en.opensuse.org/Features_15.2"
    },
    {
      "wordcount": 6314,
      "timestamp": 1620719659,
      "title": "Features 15.3",
      "snippet": "implementation of <span class=\"searchmatch\">DNF</span> called &quot;Micro <span class=\"searchmatch\">DNF</span>&quot; is included. It is designed to be used for doing simple package management actions when you don't need full-blown <span class=\"searchmatch\">DNF</span> and you",
      "url": "https://en.opensuse.org/Features_15.3"
    },
    {
      "wordcount": 1826,
      "timestamp": 1622751586,
      "title": "Release announcement 15.3",
      "snippet": "of <span class=\"searchmatch\">DNF</span> called &quot;Micro <span class=\"searchmatch\">DNF</span>&quot; is included. It is designed to be used for doing simple package management actions when users don't need a full-blown <span class=\"searchmatch\">DNF</span> and",
      "url": "https://en.opensuse.org/Release_announcement_15.3"
    },
    {
      "wordcount": 2010,
      "timestamp": 1621952115,
      "title": "Release announcement 15.3SV",
      "snippet": "stacken och förväntade förbättringar. <span class=\"searchmatch\">DNF</span> Python API är stabilt och stöds. En Experimentella &quot;opensuse/leap-<span class=\"searchmatch\">dnf</span>&quot; och &quot;opensuse/leap-microdnf&quot; bas containers",
      "url": "https://en.opensuse.org/Release_announcement_15.3SV"
    },
    {
      "wordcount": 2346,
      "timestamp": 1621951503,
      "title": "Anunci de publicació 15.3",
      "snippet": "lleugera C de <span class=\"searchmatch\">DNF</span> anomenada Micro <span class=\"searchmatch\">DNF</span>. Està dissenyada per fer accions senzilles de gestió de paquets quan els usuaris no necessitin un <span class=\"searchmatch\">DNF</span> complet i volen",
      "url": "https://en.opensuse.org/Anunci_de_publicació_15.3"
    }
  ],
  "error": null
}
```

The actual DNF entry (https://en.opensuse.org/SDB:DNF) is not there.
This is exactly what I ran into when I was experimenting with this before, and I came to the conclusion that either Mediawiki's API  sucks or our wiki is poorly configured. So it seems to me that the only way to get a functional search is to parse the result of `https://en.opensuse.org/index.php?search=<keywords>`.

**Comment by why-not-try-calmer** [comment]
Indeed, and that's something I'd like to fix upstream if that's OK for you.

**Comment by why-not-try-calmer** [comment]
Fixed as latest commit, https://github.com/openSUSE/defrag-api/pull/62/commits/e7b83591a384c9dfe9d19437a8bff9b4dbe1e0d0

**Review by KaratekHD — APPROVED** [review]
Nice

**Pull request merged**
